# Generated by Django 5.2.10 on 2026-01-16 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem_wishlist_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_completed', models.BooleanField(default=False)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetupWizardResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('store_name', models.CharField(blank=True, max_length=200)),
                ('store_tagline', models.CharField(blank=True, max_length=300)),
                ('store_email', models.EmailField(blank=True, max_length=254)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('has_stripe_account', models.BooleanField(default=False)),
                ('stripe_account_email', models.EmailField(blank=True, max_length=254)),
                ('stripe_public_key', models.CharField(blank=True, max_length=200)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=200)),
                ('ships_internationally', models.BooleanField(default=False)),
                ('domestic_shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('international_shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product_categories', models.TextField(blank=True, help_text='Comma-separated list of categories')),
                ('estimated_product_count', models.CharField(blank=True, max_length=50)),
                ('price_range_low', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_range_high', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('tiktok_handle', models.CharField(blank=True, max_length=100)),
                ('etsy_store_url', models.URLField(blank=True)),
                ('other_social', models.TextField(blank=True)),
                ('enable_reviews', models.BooleanField(default=True)),
                ('enable_wishlist', models.BooleanField(default=True)),
                ('enable_forum', models.BooleanField(default=True)),
                ('questions_for_developer', models.TextField(blank=True)),
                ('additional_features_wanted', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
