# Generated by Django 5.2.10 on 2026-01-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_adminsetupprofile_setupwizardresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='If disabled, product is always shown as in stock'),
        ),
    ]
